---
- hosts: 127.0.0.1
  connection: local

  vars_prompt:
    - name: "secrets_config"
      prompt: "Which secrets configuration to use? e.g. secrets-YOLO"
      private: no
      confirm: yes

    - name: "secrets_repo_url"
      prompt: "Which secrets repo to use? e.g. https://gogs.yolo/user/secrets-yolo.git"
      private: no

    - name: "shared_repo_url"
      prompt: "Which shared repo to use? e.g. https://gogs.yolo/user/secrets-shared.git"
      private: no

  roles:
    - { role: dotfiles }
    - { role: general, become: yes }
    - { role: sublime, become: yes }
    - { role: vim, become: yes }
    # - { role: additional, become: yes }
